[package]
name = "vrf_random_range"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.1"
stark_vrf = "0.1.1"
cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf" }

[[target.starknet-contract]]
sierra = true
